# ? ??? 'BookMarket'?? ??
spring.application.name = BookMarket
# ?? URL ?? '/BookMarket'? ??
# ?) localhost:8080/BookMarket/...
server.servlet.context-path = /BookMarket

# ??? ?? ??? ?? ?? ???????????????????????????
# Multipart Upload
# ?? ??? ??? ? (false? ??? ??)
spring.servlet.multipart.enabled = true
# 2KB ?? ??? ??? ?? ?? ??? ??
spring.servlet.multipart.file-size-threshold = 2KB
# ??? ?? ??? ?? ?? ??
spring.servlet.multipart.location = D:/upload
# ?? 1?? ?? ?? ?? (200MB ?? ? ??)
spring.servlet.multipart.max-file-size = 200MB
# ?? ?? ?? ?? (?? ?? ? ?? ??? ??)
spring.servlet.multipart.max-request-size = 215MB

# ??? ??? ?? ?? ?? ???????????????????????????
# Upload Directory
file.uploadDir = D:/upload/

# Tomcat Upload Limit
# ? ???(POST ??) ?? ??
server.tomcat.max-http-form-post-size = 200MB
# Tomcat? ???? ? ?? ?? ??? ??
server.tomcat.max-swallow-size = 200MB
# ? ??? ??? ? ?? ?? ?? ?? (50?)
server.tomcat.max-part-count = 50